# Default configuration for Garage Payment Tracker
application:
  name: "Garage Payment Tracker"
  version: "1.0.0"
  default_language: "en"
  available_languages: ["en", "ru"]

# Parsing configuration
parsing:
  grace_period_days: 3          # Days after expected date before marking overdue
  search_window_days: 7         # Days before expected date to search for payments
  date_formats:                 # Supported date formats for parsing
    - "DD.MM.YYYY"
    - "DD/MM/YYYY"
    - "YYYY-MM-DD"
    - "DD-MM-YYYY"
  amount_tolerance: 0.01        # Tolerance for amount matching (in currency units)

# Parser configuration
parsers:
  default_statement: "sberbank_excel"
  default_garage: "excel"
  available:
    - "excel"
    - "sberbank_excel"
    - "llm"  # For future implementation

# Output configuration
output:
  format: "xlsx"                # Default output format
  include_summary: true         # Include summary worksheet
  auto_open: false             # Automatically open generated reports
  filename_template: "payment_report_{timestamp}"

# Logging configuration
logging:
  level: "INFO"                 # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_enabled: true           # Enable file logging
  file_path: "logs/app.log"    # Log file path
  max_file_size: 10485760      # 10MB in bytes
  backup_count: 5              # Number of backup files to keep
  console_level: "WARNING"     # Only show warnings and errors in console

# File processing limits
limits:
  max_file_size: 52428800      # 50MB max file size
  max_rows_per_sheet: 100000   # Maximum rows to process per worksheet
  max_garages: 1000           # Maximum number of garages to process

# Feature flags
features:
  enable_llm_parsing: false    # Enable LLM-based parsing (future feature)
  enable_auto_backup: true     # Automatically backup input files
  enable_validation_warnings: true  # Show validation warnings

# Integration settings (for future features)
integrations:
  telegram:
    enabled: false
    bot_token: ""
  
  email:
    enabled: false
    smtp_server: ""
    smtp_port: 587
    username: ""
    password: ""

# Localization settings
localization:
  currency_symbol: "₽"         # Currency symbol for reports
  currency_code: "RUB"         # Currency code
  decimal_places: 2            # Decimal places for amounts
  thousands_separator: " "     # Thousands separator
  decimal_separator: ","       # Decimal separator

# Report customization
report:
  title: "Garage Rental Payment Report"
  show_logo: false
  logo_path: ""
  footer_text: "Generated by Garage Payment Tracker"
  
  # Colors for status highlighting (hex colors)
  colors:
    received: "90EE90"         # Light green
    overdue: "FFB6C1"          # Light red  
    pending: "FFFFE0"          # Light yellow
    not_due: "E6E6FA"          # Light purple
    unclear: "FFA500"          # Orange
  
  # Column widths for Excel reports
  column_widths:
    garage: 15
    amount: 18
    expected_date: 18
    actual_date: 18
    status: 15
    days_overdue: 18
    notes: 40

# Development settings
development:
  debug_mode: false
  verbose_logging: false
  skip_file_validation: false
  mock_current_date: null      # Override current date for testing (YYYY-MM-DD)
